#+TITLE: Readme

Scalaproto is a simple cli allowing conversions between scala and protobuf (proto2) formats.
It can be integrated nicely with editors (e.g. vim / Emacs).

https://docs.scala-lang.org/scala3/new-in-scala3.html

* Functionality Improvements
1. New ASTs
   - Postgresql create table
       Might be useful:
       https://chriscoffey.github.io/programming/parsing-sql-ddl-schema/
2. Scala Type support
  Scala tuple => Entry class
   - avoid name conflicts
3. Docs/UI
4. [ ] Document Emacs usage (add scalaproto.el?)
5. [ ] Add a proper CLI
6. Support Proto2 language features
7. [ ] map field (add map to common?)
8. [ ] reserved?
* Technical improvements
- [-] Make it work with GraalVM
  Done through nix
- [-] Package for nix
    Maybe some [[https://github.com/marketplace/actions/install-nix][gh actions]]?
- [ ] Release Github action

* Fixes
- add Id mode
  if ~to-scala~ then for all fields with name suffix Id add case class ~FieldId~ etc
* Ideas
-  Can scalaproto be repleaced by tree-sitter?
    https://github.com/tree-sitter

    I could be rewritten in rust.
    https://rfdonnelly.github.io/posts/using-tree-sitter-parsers-in-rust/

    Tree edit:
    https://github.com/ethan-leba/tree-edit
    https://yewtu.be/watch?v=FwDsuz0waIY
